version: '3.8'

services:
  bot:
    build: .
    container_name: my-python-bot-new
    restart: always
    volumes:
      - .:/app
    environment:
      - TELEGRAM_BOT_TOKEN  # .env fayldagi TELEGRAM_BOT_TOKEN ni oladi
      - ADMIN_ID            # .env fayldagi ADMIN_ID ni oladi
    command: python my_resume.py
